# Generated by Django 5.0.6 on 2024-05-28 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientStatus',
            new_name='Client_Status',
        ),
        migrations.RenameModel(
            old_name='ProjectStatus',
            new_name='Project_Status',
        ),
        migrations.RenameModel(
            old_name='TaskStatus',
            new_name='Task_Status',
        ),
    ]
